export const cardList = [
  {
    id: 1,
    first_name: "Maire",
    last_name: "Rayhill",
    email: "mrayhill0@wiley.com",
    gender: "Female",
    photo: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    first_name: "Iosep",
    last_name: "Gilbertson",
    email: "igilbertson1@utexas.edu",
    gender: "Male",
    photo: "http://dummyimage.com/243x100.png/cc0000/ffffff",
  },
  {
    id: 3,
    first_name: "Toby",
    last_name: "Wearne",
    email: "twearne2@51.la",
    gender: "Female",
    photo: "http://dummyimage.com/166x100.png/dddddd/000000",
  },
  {
    id: 4,
    first_name: "Isidor",
    last_name: "Courtliff",
    email: "icourtliff3@msn.com",
    gender: "Male",
    photo: "http://dummyimage.com/104x100.png/cc0000/ffffff",
  },
  {
    id: 5,
    first_name: "Gus",
    last_name: "Lofty",
    email: "glofty4@about.com",
    gender: "Male",
    photo: "http://dummyimage.com/152x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    first_name: "Vivianna",
    last_name: "Kreuzer",
    email: "vkreuzer5@slate.com",
    gender: "Female",
    photo: "http://dummyimage.com/144x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    first_name: "Paxton",
    last_name: "Peschke",
    email: "ppeschke6@prlog.org",
    gender: "Male",
    photo: "http://dummyimage.com/150x100.png/dddddd/000000",
  },
  {
    id: 8,
    first_name: "Jannelle",
    last_name: "Crompton",
    email: "jcrompton7@princeton.edu",
    gender: "Female",
    photo: "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    first_name: "Shaun",
    last_name: "Wickendon",
    email: "swickendon8@va.gov",
    gender: "Male",
    photo: "http://dummyimage.com/204x100.png/5fa2dd/ffffff",
  },
  {
    id: 10,
    first_name: "Verine",
    last_name: "O'Hartnedy",
    email: "vohartnedy9@goodreads.com",
    gender: "Polygender",
    photo: "http://dummyimage.com/183x100.png/ff4444/ffffff",
  },
  {
    id: 11,
    first_name: "Pasquale",
    last_name: "Bullard",
    email: "pbullarda@360.cn",
    gender: "Male",
    photo: "http://dummyimage.com/161x100.png/dddddd/000000",
  },
  {
    id: 12,
    first_name: "Werner",
    last_name: "MacTrustrie",
    email: "wmactrustrieb@tamu.edu",
    gender: "Male",
    photo: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
  },
  {
    id: 13,
    first_name: "Chandler",
    last_name: "Lympany",
    email: "clympanyc@google.com.au",
    gender: "Male",
    photo: "http://dummyimage.com/178x100.png/dddddd/000000",
  },
  {
    id: 14,
    first_name: "Flory",
    last_name: "McGahey",
    email: "fmcgaheyd@slideshare.net",
    gender: "Male",
    photo: "http://dummyimage.com/149x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    first_name: "Taber",
    last_name: "Titterington",
    email: "ttitteringtone@bigcartel.com",
    gender: "Male",
    photo: "http://dummyimage.com/223x100.png/ff4444/ffffff",
  },
  {
    id: 16,
    first_name: "Alaric",
    last_name: "Troup",
    email: "atroupf@census.gov",
    gender: "Male",
    photo: "http://dummyimage.com/130x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    first_name: "Dolley",
    last_name: "Dallas",
    email: "ddallasg@virginia.edu",
    gender: "Female",
    photo: "http://dummyimage.com/221x100.png/cc0000/ffffff",
  },
  {
    id: 18,
    first_name: "Rabbi",
    last_name: "Abazi",
    email: "rabazih@weebly.com",
    gender: "Male",
    photo: "http://dummyimage.com/158x100.png/dddddd/000000",
  },
  {
    id: 19,
    first_name: "Helge",
    last_name: "Scorthorne",
    email: "hscorthornei@mozilla.com",
    gender: "Female",
    photo: "http://dummyimage.com/167x100.png/cc0000/ffffff",
  },
  {
    id: 20,
    first_name: "Deena",
    last_name: "Dodd",
    email: "ddoddj@desdev.cn",
    gender: "Female",
    photo: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
  },
];
